# Generated by Django 2.2.6 on 2019-12-10 01:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Opinion',
            fields=[
                ('name', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('Opinion', models.IntegerField()),
            ],
        ),
    ]
