# Generated by Django 2.2.6 on 2019-12-10 05:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_opinion'),
    ]

    operations = [
        migrations.RenameField(
            model_name='flores',
            old_name='valor',
            new_name='precio',
        ),
        migrations.RemoveField(
            model_name='opinion',
            name='Opinion',
        ),
        migrations.AddField(
            model_name='opinion',
            name='opinion',
            field=models.TextField(default=2),
            preserve_default=False,
        ),
    ]
