# Generated by Django 2.2.6 on 2019-12-10 05:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_auto_20191210_0201'),
    ]

    operations = [
        migrations.RenameField(
            model_name='flores',
            old_name='fotografia',
            new_name='imagen',
        ),
    ]
