# Generated by Django 2.2.6 on 2019-12-12 01:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_boleta'),
    ]

    operations = [
        migrations.RenameField(
            model_name='opinion',
            old_name='opinion',
            new_name='op',
        ),
    ]
